config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "disasters#index"
  resources :disasters do
    resources :comments
  end

  namespace :admin do
    resources :types
  end

  get '/:short_url' => 'disasters#redirect'

  get '*path', to: 'disasters#not_found'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :disaster
end

app/models/disaster.rb
class Disaster < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :address


  has_many :comments
  belongs_to :user
  belongs_to :type
  mount_uploader :image, ImageUploader

  before_create :generate_unique_number

  def generate_unique_number
    loop do
      @short_num = 4.times.map{rand(9)}.join
      break unless Disaster.exists?(short_url: @short_num)
    end
    self.short_url = @short_num
  end


end

app/models/type.rb
class Type < ApplicationRecord
  validates_presence_of :category
  has_many :disasters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :comments
  has_many :disasters

  def client?
    role == 'client'
  end

  def admin?
    role == 'admin'
  end

end

app/controllers/admin/types_controller.rb
class Admin::TypesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_type, only: [:edit, :update, :destroy]

  def index
    @types = Type.all
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to admin_types_path, notice: 'Post was successfully submitted'
    else
      render :new
    end
  end

  def new
    @type = Type.new
  end

  def edit; end

  def update
    if @type.update(type_params)
      redirect_to admin_types_path
    else
      render :edit
    end
  end

  def destroy
    if @type.destroy
      redirect_to admin_types_path
    end
  end

  private

  def check_admin
    unless current_user.admin?
      flash[:notice] = "You do not have permission"
      redirect_to disasters_path
    end
  end

  def type_params
    params.require(:type).permit(:category )
  end

  def set_type
    @type = Type.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_found
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

  before_action :set_locale

  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_disaster
  before_action :set_comment, only: [:edit, :update, :destroy]


  def index
    @comments = @disaster.comments.includes(:user)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.disaster = @disaster
    @comment.user = current_user
    if @comment.save
      redirect_to disaster_comments_path(@disaster), notice: 'Comment was successfully submitted'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to disaster_comments_path(@disaster, @comment)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      redirect_to disaster_comments_path(@disaster)
    end
  end

  private

  def set_comment
    @comment = @disaster.comments.find(params[:id])
  end

  def set_disaster
    @disaster = Disaster.find params[:disaster_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_disaster, only: :show
  before_action :set_own_disaster, only: [:edit, :update, :destroy]

  def index
    @disasters = Disaster.all.includes(:user)
    @domain = request.base_url
  end

  def new
    @disaster = Disaster.new
  end

  def create
    @disaster = Disaster.new(disaster_params)
    @disaster.user = current_user
    if @disaster.save
      redirect_to disasters_path, notice: 'Post was successfully submitted'
    else
      render :new
    end
  end

  def edit; end

  def update

    if @disaster.update(disaster_params)
      redirect_to disasters_path
    else
      render :edit
    end
  end

  def show; end

  def set_own_disaster
    @disaster = current_user.disasters.find_by_id(params[:id])
    if @disaster.nil?
      flash[:alert] = 'This post not belongs to you'
      redirect_to disasters_path
    end
  end

  def destroy
    if @disaster.destroy
      redirect_to disasters_path
    end
  end

  def redirect
    @short_num = params[:short_url]
    @disaster = Disaster.find_by(short_url: @short_num)
    if @disaster.nil?
      not_found
    else
      redirect_to disaster_path (@disaster)
    end
  end

  private

  def disaster_params
    params.require(:disaster).permit(:title, :content, :address, :image, :type_id, :short_url)
  end

  def set_disaster
    @disaster = Disaster.find(params[:id])
  end

end

app/helpers/admin/types_helper.rb
module Admin::TypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/views/admin/types/edit.html.erb
<h1>Edit Post id: <%= @type.id %></h1>

<%= form_for @type, url: admin_type_path(@type), method: :patch do |f| %>
  <%= f.label :Type_of_disaster%>
  <%= f.text_area :category %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to 'Back', admin_types_path %>

app/views/admin/types/index.html.erb
<% @types.each do |type| %>
<ul>
  <li><%= type.category %></li>
  <li><%= link_to 'Edit', edit_admin_type_path(type) %></li>
  <li><%= button_to "delete", admin_type_path(type), method: :delete, data: { confirm: "Are you sure?" } %></li>
</ul>
<% end %>

<%if current_user%>
  <%= link_to 'New Type Of Disaster', new_admin_type_path %>
  <%= link_to 'Back', disasters_path %>
  <h3><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></h3>
<% else %>
  <h3><%= link_to 'Sign in', new_user_session_path %></h3>
<% end %>

app/views/admin/types/new.html.erb
<h1>Type of Disaster</h1>
  <% if @type.errors.any? %>
    <% @type.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <%= form_for @type, url: admin_types_path(@type), method: :post do |f| %>
    <%= f.label :Category %>
    <%= f.text_area :category %>
    <%= f.submit %>
  <% end %>
  <%= link_to 'back', admin_types_path %>

app/views/comments/edit.html.erb
<h1>Edit Post id: <%= @disaster.id %>, Comment ID:<%= @comment.id %></h1>

<%= form_for @comment, url: disaster_comment_path(@disaster, @comment), method: :patch do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to 'Back', disasters_path %>

app/views/comments/index.html.erb
<h1>COMMENTS</h1>

<h1><%= @disaster.id %></h1>
<ul>
  <li><%= @disaster.title %></li>
  <li><%= @disaster.content %></li>
</ul>

<table>
  <th>
  <td>id</td>
  <td>content</td>
  </th>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>
      <td><%= comment.content %></td>
      <td><%= link_to 'edit', edit_disaster_comment_path(@disaster, comment) %></td>
      <td><%= button_to "delete", disaster_comment_path(@disaster, comment), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'new', new_disaster_comment_path(@disaster) %>
<%= link_to 'Back', disasters_path %>

app/views/comments/new.html.erb
<h1>New comment for Post id<%= @disaster.id %></h1>
<%= form_for @comment, url: disaster_comments_path(@disaster), method: :post do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/disasters/edit.html.erb
<h1>Edit Post id: <%= @disaster.id %></h1>

<%= form_for @disaster, url: disaster_path(@disaster), method: :patch do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :categories %>
  <%= f.file_field :image %>
  <%= f.collection_select :type_id, Type.order(:category),:id,:category, include_blank: true %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to 'Back', disasters_path %>

app/views/disasters/index.html.erb
<h1><%= t('disaster_list') %></h1>

<table class="table text-center">
  <thead class="thead-dark">
  <tr>
    <th scope="col"><%= User.human_attribute_name(:email) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:title) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:content) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:address) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:category) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:short_url) %></th>
    <th scope="col"><%= Disaster.human_attribute_name(:image) %></th>
    <th scope="col"><%= t('common.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @disasters.each do |disaster| %>
  <tr>
    <td><%=disaster.user.email%></td>
    <td><%=disaster.title%></td>
    <td><%=disaster.content%></td>
    <td><%=disaster.address%></td>
    <td><%=disaster.type&.category%></td>
    <td><%= link_to "#{@domain}/#{disaster.short_url}", "#{@domain}/#{disaster.short_url}", target: :_self %></td>
    <td><%= image_tag "#{@domain}/#{disaster.image.url}" if disaster.image? %></td>
    <td>
      <%= link_to 'Edit', edit_disaster_path(disaster) %>
      <%= link_to "Show", disaster_path(disaster) %>
      <%= link_to :Comments, disaster_comments_path(disaster) %>
      <%= form_for disaster, url: disaster_path(disaster), method: :delete do |f| %>
        <%= f.submit 'Delete' %>
      <% end %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>


<%if current_user%>
  <%= link_to 'Create', new_disaster_path %>
  <h3><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></h3>
<% else %>
  <h3><%= link_to 'Sign in', new_user_session_path %></h3>
<% end %>

app/views/disasters/new.html.erb
<%= form_for @disaster, url: disasters_path, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category, class:'control-label' %>
    <%= f.collection_select :type_id, Type.order(:category),:id,:category, {:prompt => 'Type of Disaster'}, include_blank: true %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/disasters/show.html.erb
<ul>
  <li>Title: <%= @disaster.title %></li>
  <li>Content: <%= @disaster.content %></li>
  <li>Content: <%= @disaster.address %></li>
  <li><%= image_tag "#{request.base_url}/#{@disaster.image.url}" if @disaster.image? %></li>
</ul>

<%= link_to 'Back', disasters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <p><%= t( "hello", :name => current_user&.email)  if current_user %> </p>
    <%= link_to "English", params.permit!.merge(locale: 'en') %>
    <%= link_to "Tagalog", params.permit!.merge(locale: 'tl') %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to 'Admin', admin_types_path if current_user&.admin? %>
    <%= yield %>
  </body>
</html>